pipeline {

    agent any

    stages {

        stage('Install Dependencies') {
            steps {
                bat 'python -m pip install -r "Automation Testing/requirements.txt"'
            }
        }

        stage('Run API Tests') {
            steps {
                catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
                    bat 'python -m pytest "Automation Testing/tests/api" -n 2 --alluredir="Automation Testing/reports/allure-results"'
                }
            }
        }

        stage('Run Hybrid E2E Tests') {
            steps {
                catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
                    bat 'python -m pytest "Automation Testing/tests/e2e" -n 2 --alluredir="Automation Testing/reports/allure-results"'
                }
            }
        }

        stage('Run UI Tests') {
            steps {
                catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
                    bat 'python -m pytest "Automation Testing/tests/ui" -n 2 --alluredir="Automation Testing/reports/allure-results"'
                }
            }
        }

        stage('Generate Allure Report') {
            steps {
                allure(
                    includeProperties: false,
                    jdk: '',
                    results: [[
                        path: 'Automation Testing/reports/allure-results'
                    ]]
                )
            }
        }
    }

    post {

        always {

            archiveArtifacts(
                artifacts: 'Automation Testing/reports/screenshots/*.png',
                allowEmptyArchive: true
            )
        }

        success {

            echo 'Pipeline executed successfully.'
        }

        unstable {

            echo 'Some test cases failed. Build marked as UNSTABLE.'
        }

        failure {

            echo 'Pipeline execution failed.'
        }
    }
}
