pipeline {

    agent any

    stages {

        stage('Install Dependencies') {

            steps {

                bat 'pip install -r "Automation Testing/requirements.txt"'
            }
        }

        stage('Run API Tests') {

            steps {

                bat 'pytest "Automation Testing/tests/api" -n 2'
            }
        }

        stage('Run UI Tests') {

            steps {

                bat 'pytest "Automation Testing/tests/ui" -n 2'
            }
        }

        stage('Run Hybrid E2E Tests') {

            steps {

                bat 'pytest "Automation Testing/tests/e2e" -n 2'
            }
        }

        stage('Generate Allure Report') {

            steps {

                allure(
                    includeProperties: false,
                    jdk: '',
                    results: [[
                        path: 'Automation Testing/reports/allure-results'
                    ]]
                )
            }
        }
    }

    post {

        always {

            archiveArtifacts(
                artifacts: 'Automation Testing/reports/screenshots/*.png',
                allowEmptyArchive: true
            )
        }

        success {

            echo 'Pipeline executed successfully.'
        }

        unstable {

            echo 'Some tests failed.'
        }

        failure {

            echo 'Pipeline execution failed.'
        }
    }
}pipeline {

    agent any

    stages {

        stage('Install Dependencies') {

            steps {

                bat 'pip install -r "Automation Testing/requirements.txt"'
            }
        }

        stage('Run API Tests') {

            steps {

                bat 'pytest "Automation Testing/tests/api" -n 2'
            }
        }

        stage('Run UI Tests') {

            steps {

                bat 'pytest "Automation Testing/tests/ui" -n 2'
            }
        }

        stage('Run Hybrid E2E Tests') {

            steps {

                bat 'pytest "Automation Testing/tests/e2e" -n 2'
            }
        }

        stage('Generate Allure Report') {

            steps {

                allure(
                    includeProperties: false,
                    jdk: '',
                    results: [[
                        path: 'Automation Testing/reports/allure-results'
                    ]]
                )
            }
        }
    }

    post {

        always {

            archiveArtifacts(
                artifacts: 'Automation Testing/reports/screenshots/*.png',
                allowEmptyArchive: true
            )
        }

        success {

            echo 'Pipeline executed successfully.'
        }

        unstable {

            echo 'Some tests failed.'
        }

        failure {

            echo 'Pipeline execution failed.'
        }
    }
}
